trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: UseDotNet@2
  inputs:
    packageType: 'sdk'
    version: '8.0.x'
- script: dotnet restore
  displayName: 'Restore'
- script: dotnet build --no-restore
  displayName: 'Build'
- script: dotnet test --no-build --verbosity normal
  displayName: 'Test'
- script: docker build -t netauth:latest .
  displayName: 'Docker Build'
